# Generated by Django 3.0.3 on 2020-11-06 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_profile_uploadimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Uploadimage',
            new_name='image',
        ),
    ]
