# Generated by Django 3.0.3 on 2020-11-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20201106_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='BedNum',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='profile',
            name='HallNum',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Location',
            field=models.CharField(default='Location', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='RentCost',
            field=models.IntegerField(default='1000'),
        ),
        migrations.AddField(
            model_name='profile',
            name='kitchenNum',
            field=models.IntegerField(default='1'),
        ),
    ]
