# Generated by Django 3.0.3 on 2020-11-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20201106_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Location',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
